import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aiAgentGuideSidebar: [
    {
      type: 'link',
      label: '指南总览',
      href: '/ai-agent-engineering-guide',
    },
    {
      type: 'category',
      label: '00. 前言与阅读路径',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '前言与阅读路径',
        description: '先理解本指南的定位、阅读方式与 Semovix 的整体认知框架。',
      },
      items: [{type: 'autogenerated', dirName: '00-preface'}],
    },
    {
      type: 'category',
      label: '01. Agent 基础认知',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Agent 基础认知',
        description: '建立 Agent 的核心概念、能力边界与工程化视角。',
      },
      items: [{type: 'autogenerated', dirName: '01-agent-foundation'}],
    },
    {
      type: 'category',
      label: '02. LLM、Prompt 与 Context',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'LLM、Prompt 与 Context',
        description: '理解模型调用、提示词、上下文组织与稳定生成的基本方法。',
      },
      items: [{type: 'autogenerated', dirName: '02-llm-prompt-context'}],
    },
    {
      type: 'category',
      label: '03. Tool、Skill 与 MCP',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Tool、Skill 与 MCP',
        description: '把模型能力连接到工具、流程与外部系统。',
      },
      items: [{type: 'autogenerated', dirName: '03-tool-skill-protocol'}],
    },
    {
      type: 'category',
      label: '04. Agent Runtime 工程化',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Agent Runtime 工程化',
        description: '沉淀 Harness、Runtime、状态、恢复、验证与任务执行机制。',
      },
      items: [{type: 'autogenerated', dirName: '04-agent-runtime-engineering'}],
    },
    {
      type: 'category',
      label: '05. Semovix 语义治理场景',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Semovix 语义治理场景',
        description: '理解企业语义层、指标口径、找数问数与知识沉淀场景。',
      },
      items: [{type: 'autogenerated', dirName: '05-semovix-semantic-governance'}],
    },
    {
      type: 'category',
      label: '06. AI Workbench 产品化',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'AI Workbench 产品化',
        description: '围绕前端工作台、任务可视化、结果块与人机协同展开。',
      },
      items: [{type: 'autogenerated', dirName: '06-ai-workbench-productization'}],
    },
    {
      type: 'category',
      label: '07. 工程师成长路线',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'AI Agent 工程师成长路线',
        description: '从认知、工程到产品化能力，形成阶段性进阶路径。',
      },
      items: [{type: 'autogenerated', dirName: '07-engineer-growth-path'}],
    },
    {
      type: 'category',
      label: '08. 案例库',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: '案例库',
        description: '沉淀典型业务场景与 Semovix 相关实践案例。',
      },
      items: [{type: 'autogenerated', dirName: '08-case-studies'}],
    },
    {
      type: 'category',
      label: '09. 图解与信息图',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: '图解与信息图',
        description: '管理架构图、流程图与适合传播的知识图解。',
      },
      items: [{type: 'autogenerated', dirName: '09-diagrams'}],
    },
    {
      type: 'category',
      label: '10. 模板库',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: '模板库',
        description: '文章、图解、Skill、Tool 与案例模板。',
      },
      items: [{type: 'autogenerated', dirName: '10-templates'}],
    },
  ],
};

export default sidebars;
